### PR TITLE
Update EDA.Rmd

### PR DESCRIPTION
**Pull request by dongzhuoer**
You may need to use `smart` in Pandoc

> ``` `` ``` and '' for double quotes

https://pandoc.org/MANUAL.html#extension-smart

### CODE REVIEW

**Comment by jrnold** [comment]
Oops, forgot about that. Too many LaTeX habits; and forgetting which pandoc options I'm using in any given project.

**Comment by jrnold** [comment]
And that's weird, `smart` is enabled by default in `html_document`. It's odd that it's not in gitbook.

**Comment by dongzhuoer** [comment]
Sorry for not investigate the problem in depth.

**Comment by dongzhuoer** [comment]
The question is not that R Markdown not using smart, it is you should use the latest version of Pandoc.

```
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
```

**Comment by dongzhuoer** [comment]
To be sure, it works for either using latest Pandoc and not adding `--smart`, or using (your old pandoc) and adding `--smart`.

**Comment by jrnold** [comment]
I ended up figuring out the same thing. The multiple pandoc versions issue is annoying. I have the newest (pandoc >= 2.0.0) but Rstudio is still using (pandoc 1.19.*). I should figure out the paths issue, but have been avoided it. I may just start using Docker to build it. The other reason why using the newer pandoc would be nice is its support for fenced divs.

Btw, I do very much appreciate all the merge request/issues.

**Comment by dongzhuoer** [comment]
see `rmarkdown::pandoc_version()`. You can add your new pandoc to `PATH` or set `RSTUDIO_PANDOC` to your new pandoc.

**Comment by jrnold** [comment]
But for now, this is using the Pandoc 1.19, until I upgrade the dependencies to use pandoc 2.

**Pull request merged**
